default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: typography_test

production:
  <<: *default
  database: typography

development:
  <<: *default
  database: typography_development